service: serverless-event-trigger-examples

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev

custom:
  webpackIncludeModules: true

functions:
  scheduledEvent:
    handler: handler.scheduledEvent
    events:
      - schedule: rate(1 minute)

  s3Event:
    handler: handler.s3Event
    events:
      - s3: purplecones-events

  apiGatewayEvent:
    handler: handler.apiGatewayEvent
    events:
      - http:
          path: events/create
          method: post

  trimEventsCollection:
    handler: handler.trimEventsCollection
    events:
      - schedule: rate(10 minutes)
